# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notifications.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13notifications.proto\x12\rnotifications\"\x1c\n\x0cNotification\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\t\"<\n\x12NotificationHeader\x12\x13\n\x0b\x64\x61ta_header\x18\x01 \x03(\t\x12\x11\n\tdata_type\x18\x02 \x03(\t\"F\n\x10NotificationList\x12\x32\n\rnotifications\x18\x01 \x03(\x0b\x32\x1b.notifications.Notification\"\xa2\x01\n\x18SendNotificationsRequest\x12:\n\x11notification_list\x18\x01 \x01(\x0b\x32\x1f.notifications.NotificationList\x12>\n\x13notification_header\x18\x02 \x01(\x0b\x32!.notifications.NotificationHeader\x12\n\n\x02id\x18\x03 \x01(\x05\"\x07\n\x05\x45mpty2i\n\x13NotificationService\x12R\n\x11SendNotifications\x12\'.notifications.SendNotificationsRequest\x1a\x14.notifications.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'notifications_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NOTIFICATION']._serialized_start=38
  _globals['_NOTIFICATION']._serialized_end=66
  _globals['_NOTIFICATIONHEADER']._serialized_start=68
  _globals['_NOTIFICATIONHEADER']._serialized_end=128
  _globals['_NOTIFICATIONLIST']._serialized_start=130
  _globals['_NOTIFICATIONLIST']._serialized_end=200
  _globals['_SENDNOTIFICATIONSREQUEST']._serialized_start=203
  _globals['_SENDNOTIFICATIONSREQUEST']._serialized_end=365
  _globals['_EMPTY']._serialized_start=367
  _globals['_EMPTY']._serialized_end=374
  _globals['_NOTIFICATIONSERVICE']._serialized_start=376
  _globals['_NOTIFICATIONSERVICE']._serialized_end=481
# @@protoc_insertion_point(module_scope)
